"""New consultation (Figma "New consultation intake"): create an encounter with baseline intake and triage vitals."""
from __future__ import annotations

import secrets
from datetime import datetime

import streamlit as st
from pydantic import ValidationError

from ..auth import can
from ..repo import PermissionDenied
from ..schemas import ClinicalInputs, EncounterData, PatientProfile, Vitals
from . import common as C
from .encounters import open_encounter

_ALPHA = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
STEPS = ["Intake", "Audio", "SOAP", "Meds", "Approval"]
TYPES = ["General consultation", "Follow-up", "Maternal / child health", "Chronic disease review", "Disaster / outreach", "Other"]


def render() -> None:
    user = C.user()
    can_create = can(user, "encounter.create")
    if "nc_ref" not in st.session_state:
        st.session_state["nc_ref"] = "PT-" + "".join(secrets.choice(_ALPHA) for _ in range(6))
    now = datetime.now()
    right = C.page_header("Start New Clinical Consultation", "Capture the patient's baseline before opening the clinical workspace.")
    right.markdown(f'<div class="rs-encbox"><div class="l">Autogenerated encounter</div><div class="c">ENC-{now:%Y%m%d}-XXXX &bull; Timestamped {now:%H:%M}</div></div>',
                   unsafe_allow_html=True)
    C.show_flash()
    if not can_create:
        C.banner("Your account has the Administrator role. Administrators manage users and clinic settings, but cannot create patient encounters. To start consultations, sign in as a clinician (e.g. create a clinician account in Settings → Users & roles).", "info")
    st.markdown('<div class="rs-steps">' + "".join(
        f'<div class="st{" on" if i == 0 else ""}"><span class="n">{i + 1}</span>{s}{" <span class=cur>Current</span>" if i == 0 else ""}</div>'
        for i, s in enumerate(STEPS)) + "</div>", unsafe_allow_html=True)
    c1, c2 = st.container(key="nc_cols").columns(2, gap="medium")
    with c1, st.container(border=True):
        C.card_head("user-round", "Patient Demographics & History", "Patient reference, background and relevant history")
        st.text_input("Patient reference *", key="nc_ref", help="A clinic-assigned code. Avoid names or ID numbers. A random one is suggested.")
        st.caption("Pseudonymous identifier only — do not enter the patient's name.")
        a, b = st.columns([1.4, 1])
        age = a.number_input("Age", min_value=0.0, max_value=120.0, value=None, step=1.0, key="nc_age", format="%g")
        unit = b.selectbox("Unit", ["years", "months", "days"], key="nc_unit")
        sex = st.radio("Sex", ["unknown", "female", "male", "other"], horizontal=True, key="nc_sex",
                       format_func=lambda s: {"unknown": "Not recorded"}.get(s, s.capitalize()))
        ctype = st.radio("Consultation type", TYPES, horizontal=True, key="nc_type")
        st.caption("Allergies, chronic conditions and current medicines are recorded in the workspace intake.")
    with c2, st.container(border=True):
        C.card_head("activity", "Triage Vitals & Chief Complaint", "Initial observations and the reason for today's visit")
        st.markdown(f'<div class="rs-tblhead" style="padding:0"><div class="t" style="font-size:13px">Vital signs</div><span class="rs-small">Recorded at intake · {now:%H:%M}</span></div>',
                    unsafe_allow_html=True)
        v = st.columns(3)
        bps = v[0].number_input("BP systolic (mmHg)", min_value=40, max_value=300, value=None, step=1, key="nc_bps")
        bpd = v[1].number_input("BP diastolic (mmHg)", min_value=20, max_value=200, value=None, step=1, key="nc_bpd")
        hr = v[2].number_input("Heart rate (bpm)", min_value=20, max_value=300, value=None, step=1, key="nc_hr")
        v = st.columns(3)
        rr = v[0].number_input("Respiratory rate (/min)", min_value=4, max_value=80, value=None, step=1, key="nc_rr")
        temp = v[1].number_input("Temp (°C)", min_value=30.0, max_value=45.0, value=None, step=0.1, format="%.1f", key="nc_temp")
        spo2 = v[2].number_input("SpO2 (%)", min_value=50, max_value=100, value=None, step=1, key="nc_spo2")
        if temp is not None and temp >= 38.0:
            C.banner(f"Fever detected: {temp:.1f} °C (at or above 38.0 °C).", "warn")
        cc = st.text_area("Chief complaint", key="nc_cc", height=110, placeholder="e.g. Fever and sore throat for 2 days, with headache and body aches.")
        st.caption("Include the main symptom, onset and duration in the patient's own words.")
        st.markdown(f'<div class="rs-nextbox"><span>{C.icon_html("mic", 16, "var(--muted)")}</span><div><b>Next: audio-assisted consultation</b>'
                    '<div class="m">Review this intake before proceeding. Audio capture begins only after you enter the clinical workspace.</div></div></div>',
                    unsafe_allow_html=True)
    start = None
    with st.container(key="nc_bar"):
        b = st.columns([3, 1.3, 2], vertical_alignment="center")
        b[0].markdown(f'<div class="rs-nextbox" style="background:none;padding:0"><span>{C.icon_html("shield-check", 18, "var(--muted)")}</span>'
                      '<div><b>Pseudonymous clinical record</b><div class="m">Verify intake details before proceeding.</div></div></div>', unsafe_allow_html=True)
        if b[1].button("Save as Draft Intake", key="nc_draft", width="stretch", disabled=not can_create):
            start = "intake"
        if b[2].button("Proceed to Audio & Clinical Workspace →", key="nc_proceed", type="primary", width="stretch", disabled=not can_create):
            start = "transcript"
    if start:
        try:
            data = EncounterData(patient_ref=st.session_state["nc_ref"].strip(), consult_type=ctype,
                                 profile=PatientProfile(age_value=age, age_unit=unit, sex=sex),
                                 vitals=Vitals(bp_systolic=bps, bp_diastolic=bpd, heart_rate=hr, resp_rate=rr, temp_c=temp, spo2=spo2),
                                 inputs=ClinicalInputs(chief_complaint=cc.strip()))
            eid = C.store().create_encounter(data)
        except ValidationError as e:
            st.error("Please correct the form: " + "; ".join(x["msg"] for x in e.errors()[:3]))
            return
        except (ValueError, PermissionDenied) as e:
            st.error(str(e))
            return
        st.session_state.pop("nc_ref", None)
        C.flash(f"Encounter {eid} created.")
        open_encounter(eid, tab=start)
